import 'package:schoolmi/localization/localization.dart';
class MembersLocalization {
  final LocalizationObject inviteUsers = LocalizationObject({ Languages.NL: "Gebruikers uitnodigen"});
  final LocalizationObject participants = LocalizationObject({ Languages.NL: "Deelnemers"});
  final LocalizationObject sendInviteLink = LocalizationObject({ Languages.NL: "Stuur uitnodigingslink" });
  final LocalizationObject sendInviteLinkExtra = LocalizationObject({ Languages.NL: "Nodig je vrienden, studiegenoten of klasgenoten door een uitnodiging te versturen" });
  final LocalizationObject youAreAdmin = LocalizationObject({ Languages.NL: "Je bent een beheerder van dit netwerk" });
  final LocalizationObject youAreNotAdmin = LocalizationObject({ Languages.NL: "Je bent geen beheerder van dit netwerk" });
  final LocalizationObject membersExtra = LocalizationObject({ Languages.NL: "Bekijk leden in deze groep, beheer rechten en voeg nieuwe gebruikers toe" });
  final LocalizationObject unableToLoadUsers = LocalizationObject({ Languages.NL: "Leden konden niet worden opgehaald" });
  final LocalizationObject admin = LocalizationObject({ Languages.NL: "Beheerder" });
  final LocalizationObject noAccountMatched = LocalizationObject({ Languages.NL: "Gebruiker is uitgenodigd, maar geen account gekoppeld" });
  final LocalizationObject removeAdminRights = LocalizationObject({ Languages.NL: "Ontneem beheerrechten" });
  final LocalizationObject makeUserAdmin = LocalizationObject({ Languages.NL: "Maak gebruiker beheerder" });
  final LocalizationObject removeUserFromChannel = LocalizationObject({ Languages.NL: "Verwijder gebruiker uit netwerk" });
  final LocalizationObject addMember = LocalizationObject({ Languages.NL: "Lid toevoegen" });
  final LocalizationObject addedEmails = LocalizationObject({ Languages.NL: "Toegevoegde emails" });
  final LocalizationObject addUserMessage = LocalizationObject({ Languages.NL: "Wat is het emailadres van de gebruiker(s) die je wilt uitnodigen?" });
  final LocalizationObject membersMinimal = LocalizationObject({ Languages.NL: "Je dient tenminste 1 lid toe te voegen" });
  final LocalizationObject becomeMember = LocalizationObject({ Languages.NL: "Word lid" });
  final LocalizationObject youAreMember = LocalizationObject({ Languages.NL: "Je bent nu lid van dit netwerk" });
  final LocalizationObject leaveChannelExtra = LocalizationObject({ Languages.NL: "Klik hier om het netwerk te verlaten" });
  final LocalizationObject requiresAdmin = LocalizationObject({ Languages.NL: "Je dient een beheerder te zijn" });
  final LocalizationObject setAdminFirst = LocalizationObject({ Languages.NL: "Je dient eerst een nieuwe beheerder aan te stellen" });
  final LocalizationObject blockUserForChannel = LocalizationObject({ Languages.NL: "Blokkeer gebruiker" });
  final LocalizationObject blockUserInfo = LocalizationObject({ Languages.NL: "Weet je zeker dat je deze gebruiker wilt blokkeren? Als je de gebruiker blokkeert kan de gebruiker met het email %s geen lid meer worden van %s." });
  final LocalizationObject activeMembers = LocalizationObject({ Languages.NL: "Actieve leden" });
  final LocalizationObject blockedMembers = LocalizationObject({ Languages.NL: "Geblokkeerde leden" });
  final LocalizationObject deletedMembers = LocalizationObject({ Languages.NL: "Verwijderde leden" });
  final LocalizationObject undoDeletedFromChannel = LocalizationObject( { Languages.NL: "Herstel verwijderde gebruiker" });
  final LocalizationObject unblockFromChannel = LocalizationObject( { Languages.NL: "Deblokkeren" });
  final LocalizationObject userDeleted = LocalizationObject( { Languages.NL: "Account verwijderd" });
  final LocalizationObject userDeletedHint = LocalizationObject( { Languages.NL: "Deze gebruiker is verwijderd" });
  final LocalizationObject assignRole = LocalizationObject( { Languages.NL: "Rol toewijzen "});
  final LocalizationObject newRoleHint = LocalizationObject( {Languages.NL: "Klik om deze rol aan te maken en toe te wijzen" });
  final LocalizationObject rolesHint = LocalizationObject( { Languages.NL: "Zoek naar rollen of maak een nieuwe rol"});
  final LocalizationObject noRolesHint = LocalizationObject( { Languages.NL: "Er zijn nog geen rollen aangemaakt. Met rollen kun je aangeven wat de rol is van gebruikers in het systeem en kun je ze bij vragen en antwoorden gezamenlijk aanspreken."});
  final LocalizationObject help = LocalizationObject( { Languages.NL: "Help" });
  final LocalizationObject rolesHelp = LocalizationObject( { Languages.NL: "Met rollen kun je aangeven wat de rol is van gebruikers in het systeem en kun je ze bij vragen en antwoorden gezamenlijk aanspreken." });
  final LocalizationObject assignNoRole = LocalizationObject( { Languages.NL: "Geen rol toewijzen "});
}

