name: schoolmi
description: SchoolMi is an app that enables students and teachers to communicate 24&#x2F;7

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys().html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.2
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  scoped_model: ^1.0.1
  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.1+1
  http: ^0.12.0+2
  sprintf: ^4.0.0
  intl: ^0.15.8
  cached_network_image: ^2.2.0+1
  flutter_slidable: ^0.5.4
  page_view_indicators: ^1.3.0
  rounded_modal: ^1.0.0
  photo_view: ^0.5.0
  file_picker: ^1.4.0
  font_awesome_flutter: ^8.4.0
  image_picker: ^0.6.0+17


dev_dependencies:
  flutter_test:
    sdk: flutter

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/user.png
    - assets/vectors/tags.svg
    - assets/vectors/buildings_bg.svg
    - assets/vectors/logo.svg
    - assets/vectors/fb.svg
    - assets/vectors/google.svg
    - assets/vectors/tw.svg
    - assets/vectors/apple.svg
    - assets/vectors/home.svg
    - assets/vectors/search.svg
    - assets/vectors/profile.svg
    - assets/vectors/notification.svg
    - assets/vectors/add.svg
    - assets/vectors/arrow_right.svg
    - assets/vectors/add_image.svg
    - assets/vectors/users.svg
    - assets/vectors/logout.svg
    - assets/vectors/no_questions.svg
    - assets/vectors/user1.svg
    - assets/vectors/user2.svg
    - assets/vectors/user3.svg
    - assets/vectors/user4.svg
    - assets/vectors/user5.svg
    - assets/vectors/user6.svg
    - assets/vectors/graduation_cap.svg
    - assets/vectors/edit.svg
    - assets/vectors/tick.svg
    - assets/vectors/warning.svg
    - assets/vectors/bell.svg
    - assets/vectors/paper-plane.svg
    - assets/vectors/classroom.svg
    - assets/vectors/document.svg
    - assets/vectors/leave.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat_bold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/montserrat_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/montserrat_regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/montserrat_light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/lato_bold.ttf
          weight: 800
        - asset: assets/fonts/lato/lato_regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
